# Generated by Django 5.1 on 2024-10-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0020_alter_booking_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
    ]
